name: vgtk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - epa-ng
  - gappa
  - mafft
  - requests
  - pandas
  - biopython
  - blast=2.17.0
  - nextalign=2.14.0
